### ISSUE TITLE
GitConfigHelper setGitConfig overwrite existing bug

### ISSUE THREAD

**Issue by tmilos** [gushphp/gush#369]
Tried ```pull-request:merge``` once. It added destination repo as a new remote, the source repo as a new remote, and squashed, switched, merged... all great. 

Next time I tried again ```pull-request:merge``` on a second PR, and it again tried to add destination repo and broke with error message:
```
  [RuntimeException]
  Unable to set git config "remote.something.url" at local, because the value is already set.

gushphp\gush\src\Helper\GitConfigHelper.php:70
gushphp\gush\src\Helper\GitConfigHelper.php:132
gushphp\gush\src\Command\PullRequest\PullRequestMergeCommand.php:203
...
```

I drilled it down to ```GitConfigHelper::setGitConfig``` which says

``` 
if (hasConfig && $overwrite) {
    throw 
}
runCmd(git config set)
```

When I change it to 
``` 
if (hasConfig && false == $overwrite) {
    throw 
}
runCmd(git config set)
```
it works second time too, so bug seems to be a common typo logical switch. 

Phpunit fails both before and after this fix, with same errors as on travis builds [942](https://travis-ci.org/gushphp/gush/builds/43388142) and [943](https://travis-ci.org/gushphp/gush/builds/43388374)

Did it on gush 1.14.1, php 5.4.19, windows 7 x64, but that line (and the whole file) was not changed since added 48ba874ba8 on 2014-10-17

Will make a PR soon

**Comment by cordoval** [comment]
I just ran into the same problem after merging my second PR into gush 

~ gush p:merge 377 minor                                                    Luiss-MacBook-Pro-3 [19:57:13]

[INFO] Adding remote 'gushphp' with 'git@github.com:gushphp/gush.git' to git local config.



  [RuntimeException]
  Unable to set git config "remote.gushphp.url" at local, because the value is already set.


thanks @tmilos and sorry you have waited for so long
