### ISSUE TITLE
Plugin interface

### ISSUE THREAD

**Issue by sagikazarmark** [gushphp/gush#386]
It would be nice if anyone could write plugins to gush, so that custom workflow steps can integrate into it (without building a custom gush.phar). (For example running custom checks on a project, registering event listeners for different commands, adding custom commands to the application).

Some plugin ideas:

* Adding a repo to packagist
* Setting up githook for packagist
* Setting up travis-ci tests
* Create a repository from a boilerplate
* Add a repo to versioneye

Also, some of these commands are related to use one of the adapters (eg. github) some sort of environment dependency could be introduced (plugin depends on github adapter).

**Comment by cordoval** [comment]
thanks for your suggestions @sagikazarmark, do you have a need specific in mind? these are already possible and very specific though, so it could land as meta commands. There is a bit way though into a services approach as i was suggested sometime ago. The hook was being done with bldr-gush block, in this we could have blocks of service calls that execute what you just describe, so steps that use a class api that is more knowledgeable and stands on the shoulder of the adapter.

what are your thoughts cc @sstok

**Comment by sagikazarmark** [comment]
Well, I was thinking about my workflow and I am bit tired that I always have to setup the same hooks, same services. It would be awesome to do it with a single or a few commands.

What I usually do (by hand):

1. Set up a repo
2. Add it to packagist
3. Set up pacakgist hook
4. Add it to Travis CI
5. Add it to Scrutinizer CI (not possible through API)
6. Add it to VersionEye
7. Set up a VersionEye hook
8. Push an initial boilerplate

Pretty long, huh? (Not to mention replacing the word boilerplate to the name of the repo everywhere: badges, package names, etc)

**Comment by sagikazarmark** [comment]
So I thought some sort of plugin interface could make it possible to implement features like this. But I am new to gush, didn't check the internals, so I am open to any suggestions.

**Comment by cordoval** [comment]
version eye seemed to me a very `meta` thing, this is the reason we put it under that namespace `meta` for the commands. though now it actually is:

```
release
  release:create                 Create a new Release
  release:list                   Lists the releases
  release:remove                 Removes a release
repo
  repo:create                    Quickly spins a repository
util
  util:documentation             Generate documentation for commands in .md files.
version-eye
  version-eye:check
...
```

So those things can be expanded. They are less used to the day to day tasks. Are you releasing libraries like pancakes everyday? It seems though, if you use gush everyday and this tasks are needed, then i say  we start with the first thing, setting up a repo. The plan was laid out and we do these things very meta or have them into sections for meta commands. Now since they will have specific services I say they stay as gush commands. We should try to decouple though more and mroe things into services that contain the adapters.

**Comment by sagikazarmark** [comment]
Well, of course I am not creating libraries day to day, but I am the person
who usually do it. This is some sort of global maintainer role in the
organization.

Honestly, I dont mind if it is a plugin interface or something else.
2015.01.27. 4:17 ezt írta ("Luis Cordova" <notifications@github.com>):

**Comment by sstok** [comment]
I'd actually like something like this as well :+1: adding this to gush is possible, but using a plug-in also requires an architecture to install and enable them and thats a bigger challenge.

And I'm not completely sure if belongs to the Gush core, the repository and issue managing are part of the Git workflow so they are generic, but Packagist is more about PHP.

Should we focus on mainly PHP or should broaden the spectrum for those who use Gush but not PHP?

**Comment by cordoval** [comment]
we should broaden the spectrum since Gush will be used and is already used for projects in C#, java and others. However let's start with something. I think we should finish the tickets open then come back to this one or put this on the line. As Gush has always relied on architecture we should keep pounding it.

**Comment by sstok** [comment]
Nice :) Indeed we should start with adding something, in the beginning we only supported GitHub, then later adapters and now we can even squash a PR when merging :blush: so we have come a long way.

For plug-ins, I actually think we can use a similar architecture like Bldr.
We can't use Composer directly (as we already tried that) but using the embedded version should be an option, and then we can also fix the adapters dependency hell :dancer: 
You can still continue to use phar file and install plugin-ins with ease (`gush plugin:install packagist`).

But instead of installing in the repository we install it in the system-wide gush folder.

**Comment by sagikazarmark** [comment]
Like the idea :+1:

**Comment by cordoval** [comment]
I rather chose a different way than composer embedded, i think is little gain and is not meant to be the tool. Can we do our own? php has more power imo.

**Comment by sstok** [comment]
Any idea? :) installing is one thing, but a plug-in will most likely require an API library for communication. Which is solvable by installing that directly in the plug-in repository but will also increase the repository size and maintenance cost.

**Comment by sagikazarmark** [comment]
Probably the installing part should be left to composer. I don't think you should care about whether a plugin is installed in a project locally or globally. An example for extension handling could be phpspec.

**Comment by cordoval** [comment]
yeah i think we should only have one way which is the adapters, either turn the adapters into something like a plugin or stop calling them plugins and call them something.

**Comment by cordoval** [comment]
i am trying to avoid composer embedded because it was very painful to work with, in the sense of speed and just because is another composer like delay introduced for little gain.

**Comment by sagikazarmark** [comment]
I didn't mean composer embed. I meant it should be left to composer. You could require either the local or the global composer autoloader. However rethinking that: that is also a PHP matter.

Yeah, something is definitely a good name ;)

**Comment by sstok** [comment]
During my coffee break I actually come-up with something that can work :)
Phar files, kind of like how Java handles packages and dependencies.

Instead of referencing a composer package you install a Phar file, there just archives with executable PHP code. Just not self executable.

But the only problem is API compatibility, when plug-in A depends on API-LIBv1 and provides this with the archive. How do we prevent plug-in B which depends on API-LIBv2 from breaking?
I know PHPUnit had a similar problem in the past with depending on the Symfony Yaml component and testing a Symfony version which provided an older version, there idea was to include an embedded version with a custom namespace. But how do you automate something like that :dizzy_face:

But we should properly focus on the DI services first and then when have some stable extension points we can start thinking about how to install external packages and hooking/plugging them into the system. Thats properly the biggest challenge :)

**Comment by cordoval** [comment]
:coffee:

**Comment by sstok** [comment]
At least for Scrutinizer there is good news. Its now possible to add repositories using the API :+1: 
https://scrutinizer-ci.com/docs/api/#adding-github-repository

**Comment by sagikazarmark** [comment]
I am thinking about writting an API client for scrutinizer, but I am not sure I want to develop a fully featured HAL client. Looking at https://github.com/willdurand/Hateoas right now, but I think it's just a builder and not a client. Any ideas?

**Comment by cordoval** [comment]
perhaps all we need i think is to allow an include to define new commands written in the form of an array of callbacks cc @sstok, if i need more dependencies that would be up to me to require them inside a subfolder with all needed and the autoload required in the callback. We should perhaps write in the callback format the original commands as to demo the purpose. I am closing this ticket and opening a new ticket more geared towards this approach.
