### ISSUE TITLE
Config not recognized after upgrade to 1.16.1

### ISSUE THREAD

**Issue by aik099** [gushphp/gush#495]
I've upgraded to 1.16.1 version and while attempting to run `gush issue:task 51` I've getting an exception that my config (the `gush.yml` file in `~/.gush` folder) is no good:

```
[ERROR] The adapter type could not be determined.The following adapters (may support this repository) but are currently
 not configured: "github", "github_enterprise", "bitbucket", "gitlab". Please configure the adapters or run the         
 "core:init" command.
```

I've tried to run `gush core:init`, but it's asking some new questions, like organization name and such, that were not asked when I've executed this command in previous Gush versions. I have absolutely no idea what to answer in these questions. And if I don't answer anything (except that I'm using GitHub), then another exception is thrown.

**Comment by sstok** [comment]
Since #416 (1.16.0 at minimum) a great number of things have changed.

* First you need run `core:configure` as the original configuration format has changed (*I actually need open a issue about this so we can warn when this happens*).

Gush should be able to determine the org and repository by the remote origin of your repository.
Don't worry if it points to a fork as this is automatically resolved :+1: 

But sometimes it will fail to determine this (no remote origin, adapter not configured or enterprise/self hosting) and you need configure this manually using the `core:init` command (which you need run from the local Git repository).

**Note:** Support for GitHub Enterprise and GitLab self-hosted is still incomplete ( #462 )

If you are outside a Git enabled folder (or no remote origin is set) then you need tell Gush which repo/issue-tracker adapter and organization you are using `--repo-adapter=github --isssue-tracker=github --org=your-org --repo=your-repository`.

**Comment by aik099** [comment]
> First you need run core:configure as the original configuration format has changed (I actually need open a issue about this so we can warn when this happens).

I've already entered all the info back then and entering it once again after upgrade seems like unnecessary knowing that Gush knows how settings were transformed and it could migrate them. Right now I'm getting same error message as if `.gush.yml` file wasn't created at all, which is confusing.

> Gush should be able to determine the org and repository by the remote origin of your repository.
Don't worry if it points to a fork as this is automatically resolved

So I should run `gush core:init` or `gush core:configure` to migrate config to new format?

**Comment by sstok** [comment]
You need to run `gush core:configure` first to update your system-wide configuration.
Then you *may* need to run `gush core:init`, when the adapter is configured Gush should be able to automatically determine the values.

`gush core:init` is not always mandatory but it does improve the speed and saves a couple of API calls ;)

**Comment by cordoval** [comment]
I just got into using gush for gitlab again and the only thing that is not working is simultaneously using Gitlab and Gitlab enterprise. However I just configured it with just github private and it works. Please feel free to reopen a more specific issue if you have troubles. Also make sure you use the latest gush version since we don't maintain release branches. Regarding the configurations, they are not hard to enter again even though we will now be more respectful of BC changes.
