### ISSUE TITLE
Too many BC breaks between minor versions

### ISSUE THREAD

**Issue by pierredup** [gushphp/gush#497]
One of the reasons I don't really use Gush is because of all the BC breaks between versions.
Every now and then there is a change in how something works (see #495) or the minimum version of PHP is updated (#469 and [494#issuecomment-143863957](https://github.com/gushphp/gush/issues/494#issuecomment-143863957)) and @cordoval even said he doesn't care about BC ([416#issuecomment-94829006](https://github.com/gushphp/gush/issues/416#issuecomment-94829006)).

This makes it a pain to work with Gush, and you are also limited to the way gush decides to do the workflow, instead of being able to use your own workflow (I constantly need to add the --org parameter because gush doesn't care about my upstream repository).

So my proposal would be to have a stable version where BC is guaranteed and any future changes would need to add a BC layer which can be removed in the next major update.

Also (which might be a bit more work) have a way to define custom workflows so you are not restricted to only the workflow gush decides on

**Comment by sstok** [comment]
Thanks for bringing this up :+1: 

I agree that as community we should focus more on: stability, backward compatibility (including minimum php version), and less on breaking features (note that #462 was done to once and for all make it easier to use Gush, but it was allot of work :flushed: ).

> This makes it a pain to work with Gush, and you are also limited to the way gush decides to do the workflow, instead of being able to use your own workflow (I constantly need to add the --org parameter because gush doesn't care about my upstream repository).

This is actually fixed in #462 :) *it doesn't work for the --source-org yet*.
Supporting alternative workflows is definitely something we need to look into, some work is already done and `branch:merge` does actually have basic implementation to do this (validation only at the moment). - Please open a separate issue to discuss this further ;)

About the breakages;

I actually suggested (in chat with @cordoval) to do a 2.0 version with some major refactoring which we had for a while but it introduced to many maintenance problems (so it was reverted).

* The PHP 5.5 was actually done to make testing easier, but I can revert this (hopefully using a custom PHP-cs fixer :yum: ); We were under the assumption that a development machine had a higher PHP version now a days.
* Rebuilding configuration is cheap, but it does mean work and should not be done in minor versions (unless it fixes a serious bug).
* #462 would actually cause some major breakage as well, so this needs to be avoided!

For the future we can do the following (and make sure we hold our selfs to this promise);
*See this as code of conduct.*

As Gush is getting more and more used by developers (that rely on Gush for daily workflow) it is important to fulfill this promise and not introduce breaking changes between minor versions!
**We as a *team* must follow these principles and apply them consistently (yes it's hard to do this, but the result is what matters).**

* Fully adapt Semver 2.0! (it's said we follow this, but so it's not the case right now).
* Clearly mention what is changed in a release (including deprecations).
* Keep track of all BC changes in a Changelog/Upgrade file.

Further, any changes to how Gush is used are a backward compatibility break and can only be done in a new major version:

* Don't bump PHP versions between minor versions (except minor php versions bumps to fix an unresolvable bug).
* No renaming/removing of options, arguments and commands.
* Don't change the (complete) configuration schema (except on a per-adapter bases to fix a bug).

For quality: 

* Tests are required for any new feature or bug fix (period), except for adapters (at the moment) which is harder.
* We can use AppVeyor for testing on Windows?
* All changes must be done using pull-requests
  * Wait for the Continues Integration to complete!
  * Any functional changes require a `:+1:` from someone who knows enough about the subject.
  * If it takes to long to get a `:+1:` ping a teammate;
  * If you think it's good enough, give your vote and allow other teammates to check also (with respect to timezones and availability).

Gush is a community project, we are all responsible for the quality of the project and *will* point other teammates on not following the compatibility promise or doing big changes without discussing with other teammates or users. Not even the head owner can apply major changes without properly discussing this first! :+1: 

-----

These idea's can only ever work if we as a team follow them.
Please discuss other suggestions and idea's to improve our development workflow and principals.

*Note that I'm only doing this in the interest for the Gush project, I'm not attacking anyone personally :dancer:*

**Comment by pierredup** [comment]
> We were under the assumption that a development machine had a higher PHP version now a days.

I personally run PHP 5.6 everywhere, but that is not the case with everyone. I know most people mimic the version of PHP used on production on their development machines, so that there is no inconstancy between development and production (E.G running 5.5 in development you are tempted to use 5.5 specific features, which would break if production only runs 5.4).

Further I completely agree with your proposal. I think Gush has the potential to be an awesome tool that a lot of developers will use, which is the only reason I brought this up, because I want to see more people using it and getting involved with the least pain possible.

**Comment by cordoval** [comment]
I agree with @pierredup and @sstok, discussion is open and retorts can come at anytime. Since this issue is more of an invitation to discussion and the rules are clear I am closing this.
