### ISSUE TITLE
[security] cert copied to world writable dir using known name

### ISSUE THREAD

**Issue by glensc** [gushphp/gush#531]
https://github.com/gushphp/gush/blob/1.18.1/phar-stub.php#L18

i think this is security issue, vector for symlink attacks and who knows what else.
better safe than sorry.
if that copy i still necessary, better use some user owned paths (not word writable ones), $HOME for example.

other options is to use [tempnam](http://php.net/manual/en/function.tempnam.php), but then should remember to clean up.

**Comment by sstok** [comment]
Thanks for reporting this :+1: will look into it.

**Comment by cordoval** [comment]
What scenario you envision for attacks, i am not sure i follow.
This is actually corresponding to guzzle package since the file and things come from guzzle, is there a ticket in guzzle that treats this problem? if not i believe that is where it should start no?

**Comment by glensc** [comment]
it's general security-wise knowledge that you should not use files that ANYBODY in system can control (write).

how to use it for explotation, is up to attackers, they can probably figure something out :)

attack likely needs to be combination of several vectors, like forge dns server to point github.com to ip under attackers control, and then use rogue https cert there, but as ca file is under attacker control, you won't notice you download modified software from fake github server.

**Comment by cordoval** [comment]
I see, gush is more of a personal tool, so this file is in your laptop that only you are suppose to control. 
Maybe as you say we should just write it to ~ but if someone has access to your laptop then it can also access ~ home. I think we should move this concern to guzzle, since there are 37 hundred usages out there https://github.com/search?q=guzzle-cacert.pem&type=Code&utf8=%E2%9C%93 :blush: 

Please link us here back so we follow up on the concern on guzzle.

**Comment by glensc** [comment]
you did not pay attention, /tmp is world writable, thus any user in the system can write it. think of shared hosting sites.

but whatever, i'm not here to convince you over.

**Comment by pierredup** [comment]
> any user in the system can write it. think of shared hosting sites

Gush is a development tool, it is not meant to be run anywhere than on your local machine. It shouldn't be added to a server, a shared hosting site, a CI build tool etc. It is only meant to be run on your local development computer.
So the fact that `/tmp` is world writable, means only people that have access to your PC can access the file. And if someone you don't trust has access to your PC, then there is more to worry about than the certificate file from Guzzle, because then they can steal all your passwords or any other information stored on your PC

**Comment by glensc** [comment]
you sound like gush is windows centric. can have more users on my linux box than me, and still be protected as they are regular users having no access to my $HOME

**Comment by sstok** [comment]
It's simple enough to fix this, lets keep this open. I will work on it tomorrow :+1:

**Comment by cordoval** [comment]
The problem won't be solved like this. I think we have to escalate to guzzle it so i will create the ticket on guzzle and refer back to this.

**Comment by cordoval** [comment]
That is where we need to address the problem https://github.com/guzzle/guzzle3/issues/71, either there or in their documentation. It is more responsible since i see a lot of people doing this.

**Comment by pierredup** [comment]
I think the problem here is using an old and unmaintained version of Guzzle.
Gushg should be updates to use the latest version of Guzzle

**Comment by sstok** [comment]
@pierredup Gush uses Guzzle itself only for downloading patches (pull-request:) and it's used by the GitHub adapter (which can't upgrade).

Even we upgrade Guzzle, the GitHub adapter (and properly others) will still use the old version
