### ISSUE TITLE
New approach for pull-request:create template

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#561]
At the moment we support a simple questioner for the Pull-request template, and a description at the bottom. 

There are however two problems with this system:

* Typo's can't be easily fixed as support for readline was removed (because it was broken...)
* GitHub has been greatly improved since support for this was added. You can now add a PULL_REQUEST template in your repository, which provides a template (like Gush's).

  And it's possible to use HTML comments to give instructions, like Sonata does in https://raw.githubusercontent.com/sonata-project/dev-kit/master/project/.github/PULL_REQUEST_TEMPLATE.md

Using a template gives much more power, and it will (when instructions are provided and actually followed) ensure questions are correct (to often I see in the Symfony project that questions are left as `yes/no`).

So what I propose: 

* add support for using, eg. a template (opening the EDITOR) or the questioner (consider deprecating the questioner).
* automatically remove HTML comments from the description when merging the pull-request, this will require a proper markdown parser as code-blocks may contain HTML with comments as well.

[PULL_REQUEST_TEMPLATE.txt](https://github.com/gushphp/gush/files/380206/PULL_REQUEST_TEMPLATE.txt)

**Comment by cordoval** [comment]
I think complicates the fact that p:create just creates a PR, if you want to do PRs with github then that is a separate issue. Gush should keep it simple, it is already a complication to have it do something on a template.

However I see that @phansys have already fixed some concerns you listed here. So this ticket can perhaps be closed since all the problems were solved.
