### ISSUE TITLE
dockerize

### ISSUE THREAD

**Issue by cordoval** [gushphp/gush#566]
https://github.com/gushphp/gush/pull/565

**Comment by shulard** [comment]
Hello !

I checked the `Dockerfile` and found that you ran multiple `RUN` statements. Why ? Each `RUN` create a new docker layer, I think it'll be simpler to make something like this :

```Dockerfile
FROM php:7.0.8-alpine

COPY . /usr/src/gush
WORKDIR /usr/src/gush

RUN set -xe \
    && apk add --no-cache git \
    && curl -s https://getcomposer.org/installer | php && \
    && chmod +x composer.phar && mv composer.phar /usr/bin/composer \
    && composer install

ENTRYPOINT ["/usr/src/gush/gush"]
```

Also I suggest to remove the `CMD` directive. I think it's better to view command list instead of `--help` as default...

**Comment by cordoval** [comment]
only couple of things left are to write back to the .gush/.gush.yml file, cc @gushphp/contributor welcome PRs for that for sure!
