### ISSUE TITLE
remove more commands?

### ISSUE THREAD

**Issue by cordoval** [gushphp/gush#624]
i believe there is room for removing more commands, PRs welcome

**Comment by sstok** [comment]
FYI, I do use the `pull-request:styleci` command.

The `MetaHeaderCommand` could be moved to it's own mini-application, because it doesn't depend on the Adapters (only on Git to get a list of versioned files).

**Comment by glensc** [comment]
wtf? why? please suggest what else to use instead of gush as alternative as this project seems to became nonsense.

**Comment by cordoval** [comment]
@glensc some commands are really obsolete, like the fabbot, some things that are really not used. That is also why the ticket to ask to be more careful.

**Comment by glensc** [comment]
how are you to decide what is used and what is not. i could understand dropping integration of service that is no longer available. but dropping jira support (#557)... wtf?

**Comment by cordoval** [comment]
I explained on the ticket #557.

**Comment by glensc** [comment]
http://fabbot.io/ is still there. what you mean obsolete? if you keep removing commands you're driving people off, that nobody should be able to fix if there's api incompatibility which could be fixed by contributors by submitting PR

if you wish to disable commands that are broken, just [do not register them](https://github.com/gushphp/gush/blob/1.19.1/src/Application.php#L313-L357), but keep the code around so it could be fixed later by contributors etc

**Comment by cordoval** [comment]
Things can be added back without much problem because of git. Will keep in mind to be more careful but some changes have and will be made to improve gush in the long run.

**Comment by glensc** [comment]
you will lose file history if you add them back, the added files will not "see" the commits they had before removal.

**Comment by cordoval** [comment]
history on the same file yes, but you can always track the history.
